<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBuqqx3v\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBuqqx3v/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBuqqx3v.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBuqqx3v\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBuqqx3v\appProdProjectContainer([
    'container.build_hash' => 'Buqqx3v',
    'container.build_id' => 'df1e51af',
    'container.build_time' => 1660051015,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBuqqx3v');
